Repository OASIS-HWORLD/hworld-spring, pull requests merged in 2024-09, with the labels that each got.

#11 [CONTEST] 콘테스트 게시글 목록 조회 필터링 기능 구현
  src/main/java/com/oasis/hworld/contest/controller/ContestController.java
  src/main/java/com/oasis/hworld/contest/mapper/ContestMapper.java
  src/main/java/com/oasis/hworld/contest/service/ContestService.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
Labels: :sparkles: feat

#16 [CONTEST] 콘테스트 게시글 상세보기 기능 구현
  src/main/java/com/oasis/hworld/common/exception/ErrorCode.java
  src/main/java/com/oasis/hworld/contest/controller/ContestController.java
  src/main/java/com/oasis/hworld/contest/dto/ItemDTO.java
  src/main/java/com/oasis/hworld/contest/dto/PostDetailResponseDTO.java
  src/main/java/com/oasis/hworld/contest/dto/ReplyDTO.java
  src/main/java/com/oasis/hworld/contest/mapper/ContestMapper.java
  src/main/java/com/oasis/hworld/contest/service/ContestService.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
Labels: :sparkles: feat

#22 [MEMBER] 로그인 구현
  pom.xml
  src/main/java/com/oasis/hworld/common/exception/ErrorCode.java
  src/main/java/com/oasis/hworld/member/controller/MemberController.java
  src/main/java/com/oasis/hworld/member/domain/Member.java
  src/main/java/com/oasis/hworld/member/dto/LoginRequestDTO.java
  src/main/java/com/oasis/hworld/member/dto/LoginResponseDTO.java
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/member/service/AuthService.java
  src/main/java/com/oasis/hworld/member/service/AuthServiceImpl.java
  src/main/java/com/oasis/hworld/security/dto/JwtTokenDTO.java
  src/main/java/com/oasis/hworld/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/oasis/hworld/security/jwt/JwtTokenProvider.java
  src/main/java/com/oasis/hworld/security/service/CustomUserDetails.java
  src/main/java/com/oasis/hworld/security/service/CustomUserDetailsService.java
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: :sparkles: feat

#26 [MEMBER] MemberId 어노테이션 추가
  src/main/java/com/oasis/hworld/common/annotation/MemberId.java
  src/main/java/com/oasis/hworld/common/resolver/MemberIdArgumentResolver.java
  src/main/java/com/oasis/hworld/security/jwt/JwtAuthenticationFilter.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: :sparkles: feat

#45 [MEMBER] 마이페이지 내 코디 목록 조회
  src/main/java/com/oasis/hworld/member/controller/MemberController.java
  src/main/java/com/oasis/hworld/member/dto/CoordinationItemListResponseDTO.java
  src/main/java/com/oasis/hworld/member/dto/CoordinationListResponseDTO.java
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/member/service/MemberService.java
  src/main/java/com/oasis/hworld/member/service/MemberServiceImpl.java
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
Labels: :sparkles: feat

#48 [MEMBER] 마이페이지 구매 내역 조회
  src/main/java/com/oasis/hworld/member/controller/MemberController.java
  src/main/java/com/oasis/hworld/member/dto/OrdersDetailResponseDTO.java
  src/main/java/com/oasis/hworld/member/dto/OrdersItemDTO.java
  src/main/java/com/oasis/hworld/member/dto/OrdersListResponseDTO.java
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/member/service/MemberService.java
  src/main/java/com/oasis/hworld/member/service/MemberServiceImpl.java
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
Labels: :sparkles: feat

#53 [COORDINATION] 코디 모듈 구현
  src/main/java/com/oasis/hworld/character/domain/CharacterItem.java
  src/main/java/com/oasis/hworld/coordination/controller/CoordinationController.java
  src/main/java/com/oasis/hworld/coordination/domain/Coordination.java
  src/main/java/com/oasis/hworld/coordination/domain/CoordinationItem.java
  src/main/java/com/oasis/hworld/coordination/dto/CoordinationItemRequestDTO.java
  src/main/java/com/oasis/hworld/coordination/dto/CoordinationRequestDTO.java
  src/main/java/com/oasis/hworld/coordination/mapper/CoordinationMapper.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationService.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationServiceImpl.java
  src/main/resources/com/oasis/hworld/coordination/mapper/CoordinationMapper.xml
Labels: :sparkles: feat

#50 [CONTEST] 콘테스트 게시글 삭제 기능 구현
  src/main/java/com/oasis/hworld/contest/controller/ContestController.java
  src/main/java/com/oasis/hworld/contest/mapper/ContestMapper.java
  src/main/java/com/oasis/hworld/contest/service/ContestService.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
Labels: :sparkles: feat

#55 [COORDINATION] 코디 삭제 구현
  src/main/java/com/oasis/hworld/coordination/controller/CoordinationController.java
  src/main/java/com/oasis/hworld/coordination/mapper/CoordinationMapper.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationService.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationServiceImpl.java
  src/main/java/com/oasis/hworld/member/controller/MemberController.java
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/member/service/MemberService.java
  src/main/java/com/oasis/hworld/member/service/MemberServiceImpl.java
  src/main/resources/com/oasis/hworld/coordination/mapper/CoordinationMapper.xml
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
Labels: :sparkles: feat

#57 [COORDINATION] 코디 상품 조회 구현
  src/main/java/com/oasis/hworld/coordination/controller/CoordinationController.java
  src/main/java/com/oasis/hworld/coordination/dto/CoordinationItemResponseDTO.java
  src/main/java/com/oasis/hworld/coordination/mapper/CoordinationMapper.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationService.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationServiceImpl.java
  src/main/resources/com/oasis/hworld/coordination/mapper/CoordinationMapper.xml
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
Labels: :sparkles: feat

#59 [COORDINATION] 장바구니 조회 관련 쿼리문 수정
  src/main/java/com/oasis/hworld/coordination/mapper/CoordinationMapper.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationServiceImpl.java
  src/main/resources/com/oasis/hworld/coordination/mapper/CoordinationMapper.xml
Labels: enhancement

#52 [SHOP] 상점의 상품 목록 조회 기능
  src/main/java/com/oasis/hworld/common/domain/ItemCategory.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/java/com/oasis/hworld/shop/controller/ShopController.java
  src/main/java/com/oasis/hworld/shop/domain/Shop.java
  src/main/java/com/oasis/hworld/shop/dto/ShopItemDTO.java
  src/main/java/com/oasis/hworld/shop/mapper/ShopMapper.java
  src/main/java/com/oasis/hworld/shop/service/ShopService.java
  src/main/java/com/oasis/hworld/shop/service/ShopServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
  src/main/resources/com/oasis/hworld/shop/mapper/ShopMapper.xml
Labels: :sparkles: feat

#64 [QUEST, PAYMENT] 퀘스트 진행 추가, 포인트 적립/차감 추가
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/payment/controller/PaymentController.java
  src/main/java/com/oasis/hworld/payment/service/PaymentService.java
  src/main/java/com/oasis/hworld/payment/service/PaymentServiceImpl.java
  src/main/java/com/oasis/hworld/quest/controller/QuestController.java
  src/main/java/com/oasis/hworld/quest/domain/QuestProgress.java
  src/main/java/com/oasis/hworld/quest/mapper/QuestMapper.java
  src/main/java/com/oasis/hworld/quest/service/QuestService.java
  src/main/java/com/oasis/hworld/quest/service/QuestServiceImpl.java
  src/main/resources/com/oasis/hworld/cart/mapper/CartMapper.xml
  src/main/resources/com/oasis/hworld/deliveryaddress/mapper/DeliveryAddressMapper.xml
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
  src/main/resources/com/oasis/hworld/payment/mapper/PaymentMapper.xml
  src/main/resources/com/oasis/hworld/quest/mapper/QuestMapper.xml
Labels: :sparkles: feat

#71 [COMMON] CORS 필터 설정
  src/main/java/com/oasis/hworld/filter/CorsFilter.java
  src/main/webapp/WEB-INF/spring/security-context.xml
Labels: :sparkles: feat

#78 [COMMON] S3 이미지 업로드 추가, 베스트 코디 조회 추가
  pom.xml
  src/main/java/com/oasis/hworld/common/file/S3Config.java
  src/main/java/com/oasis/hworld/common/file/S3Uploader.java
  src/main/java/com/oasis/hworld/contest/controller/ContestController.java
  src/main/java/com/oasis/hworld/contest/mapper/ContestMapper.java
  src/main/java/com/oasis/hworld/contest/service/ContestService.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/java/com/oasis/hworld/coordination/controller/CoordinationController.java
  src/main/java/com/oasis/hworld/coordination/dto/CoordinationRequestDTO.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationService.java
  src/main/java/com/oasis/hworld/coordination/service/CoordinationServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: :sparkles: feat

#80 [MEMBER] 마이페이지 관련 api 수정
  src/main/java/com/oasis/hworld/member/controller/MemberController.java
  src/main/java/com/oasis/hworld/member/dto/OrdersListResponseDTO.java
  src/main/java/com/oasis/hworld/member/dto/PageResponseDTO.java
  src/main/java/com/oasis/hworld/member/mapper/MemberMapper.java
  src/main/java/com/oasis/hworld/member/service/MemberService.java
  src/main/java/com/oasis/hworld/member/service/MemberServiceImpl.java
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
Labels: enhancement, :sparkles: feat

#81 [CONTEST] 콘테스트 게시판 관련 API 수정
  src/main/java/com/oasis/hworld/contest/controller/ContestController.java
  src/main/java/com/oasis/hworld/contest/dto/PostAwardDTO.java
  src/main/java/com/oasis/hworld/contest/mapper/ContestMapper.java
  src/main/java/com/oasis/hworld/contest/service/ContestService.java
  src/main/java/com/oasis/hworld/contest/service/ContestServiceImpl.java
  src/main/resources/com/oasis/hworld/contest/mapper/ContestMapper.xml
Labels: enhancement, :sparkles: feat

#84 [SHOP] 아이템 상세 조회 구현
  src/main/java/com/oasis/hworld/shop/controller/ShopController.java
  src/main/java/com/oasis/hworld/shop/dto/ItemDetailResponseDTO.java
  src/main/java/com/oasis/hworld/shop/mapper/ShopMapper.java
  src/main/java/com/oasis/hworld/shop/service/ShopService.java
  src/main/java/com/oasis/hworld/shop/service/ShopServiceImpl.java
  src/main/resources/com/oasis/hworld/member/mapper/MemberMapper.xml
  src/main/resources/com/oasis/hworld/shop/mapper/ShopMapper.xml
Labels: :sparkles: feat
